# Dataset paths - maps dataset names to their directories
[datasets]
replogle_h1 = "./competition_support_set/{competition_train,k562_gwps,rpe1,jurkat,k562,hepg2}.h5"

# Training specifications
# All cell types in a dataset automatically go into training (excluding zeroshot/fewshot overrides)
[training]
replogle_h1 = "train"

# Zeroshot specifications - entire cell types go to val or test
[zeroshot]
"replogle_h1.hepg2" = "test"


# Fewshot specifications - explicit perturbation lists
[fewshot]

# New: Cell-eval configurations
[cell_eval]
enabled = true
eval_every_n_steps = 1  # all 50 steps evaluation
plot_every_n_evals = 1
eval_metrics = ['overlap_at_N', 'mae', 'discrimination_score_l1']
save_predictions = true
verbose = true

[model]
name = "pertsets"

[model.kwargs]
cell_set_len = 64
hidden_dim = 328
