wandb_track: true
weight_decay: 0.0005
batch_size: 16
lr: 1e-4
max_steps: 40000
train_seed: 42
val_freq: 2000
ckpt_every_n_steps: 2000
gradient_clip_val: 10 # 0 means no clipping
loss_fn: mse
devices: 1  # Number of GPUs to use for training
strategy: auto  # DDP strategy for multi-GPU training
use_mfu: true
mfu_kwargs:
    available_flops: 60e12
    use_backward: true
    logging_interval: 10
    window_size: 2
cumulative_flops_use_backward: true